### ISSUE TITLE
Error: EPERM: operation not permitted, when download file

### ISSUE THREAD

**Issue by batis97** [andresusanto/easydl#14]
I have a problem with a Windows device, when the file download process is running, suddenly the process stops and an error appears [easydl][catch2] > Error: EPERM: operation not permitted, stat 'C:\Users\xxx\AppData\Local\ Temp\downlaodfolder\appfolder\downloadfile.zip.$$7'

and when I close, then download again, the download process is stuck and there is an error: [error] [Corrupted] when downloading downloadfile.zip

can you provide a solution for this problem?

**Comment by andresusanto** [comment]
I've pushed some bugfixes in `v1.1.0` that might address this issue, can you update and verify is that one solves this issue please?
