### ISSUE TITLE
existBehavior = 'ignore' - no events are emitted?

### ISSUE THREAD

**Issue by PlkMarudny** [andresusanto/easydl#5]
It seems  to me that no events are emitted if the file exists and existBehavior = 'ignore', is this by design?

**Comment by andresusanto** [comment]
@PlkMarudny that is right, it is by design to allow several use cases that need this behaviour.

I think what would be nice is to have `existBehavior` = `error`. I will find some time to implement it, also feel free to make a pull request if you have something being worked on already.

**Comment by PlkMarudny** [comment]
Thanks, I will take a look at it.

**Comment by andresusanto** [comment]
Implemented on version `1.1.0`
